/* ==========================================================================
 * console.h -- the X816 console: VERA text out, SMC keyboard in.
 *
 * This is the kernel's console layer, specified in X816_Core doc/KERNEL.md
 * §5.1. It owns the text screen when no program has taken it, which is what
 * puts it kernel-side under §2.1 test 1 -- two copies would fight over the
 * screen and the keyboard queue.
 *
 * 80x60 at 640x480, 1bpp tile mode with per-cell attributes: the same VERA
 * setup already proven on hardware by X816_Core boot/hello.s, rather than a
 * fresh one.
 *
 * BUILD AT -O0. Every one of these functions reaches VERA and the VIA through
 * volatile registers, and Calypsi 5.18 eliminates volatile reads at -O1 and
 * above -- see the README.
 * ========================================================================== */

#ifndef CONSOLE_H
#define CONSOLE_H

#include <stdint.h>
#include <stdbool.h>
#include "x816_contract.h"

#define CON_COLS 80
#define CON_ROWS 60

/* Sets up VERA, uploads the font and clears the screen. Call once. */
void con_init(void);

void con_cls(void);

/* ALL 256 codes have a glyph: CP437, generated by X816_core/tools/mkfont.py.
 * $20-$7E is ASCII including lower case, $80-$FF is CP437's accented letters,
 * box drawing, blocks and maths. Only the control codes below are intercepted:
 *     \n  newline, scrolling at the bottom
 *     \r  carriage return, column 0
 *     \b  backspace, non-destructive at column 0
 */
void con_putc(char c);
void con_puts(const char *s);

/* Through a 24-bit pointer: the kernel ABI hands strings over as address plus
   bank, and a near pointer cannot leave bank $00. */
void con_puts_far(const char __far *s);

/* Place one glyph by CODE, with no interpretation at all.
 *
 * con_putc intercepts $08, $0A and $0D as backspace, newline and carriage
 * return, so those three glyphs are unreachable through it -- and CP437 has
 * real pictures there. Anything drawing with the box, block or control-code
 * glyphs wants this instead: it moves no cursor and interprets nothing. */
void con_putraw(uint8_t x, uint8_t y, uint8_t ch);

/* The same thing for a RUN of characters, with the VERA address set once
 * instead of once per glyph -- 3 + 2n accesses against 6n.
 *
 * For TEXT: a status line, a help line, a row being cleared. Measured with the
 * millisecond timer, con_putraw is 90 us a character, so this is a real 3x on
 * anything that draws a line at a time.
 *
 * It is NOT a fix for a slow screen. Switching a spreadsheet's 364 ms repaint
 * to this took it to 358 ms, because that repaint was dominated by formatting
 * floats into columns rather than by writing characters. console.c's own
 * comment carries the numbers. */
void con_putrun(uint8_t x, uint8_t y, const char *s, uint8_t n);

/* The same run out of a 24-bit pointer, for a caller whose characters live in
 * a bank a near pointer cannot name -- a cache in BRAM, a buffer in the
 * allocator's arena.
 *
 * Use it rather than staging into bank $00 first. Staging eighty bytes cost
 * MORE than writing them: a fully cached 56-row spreadsheet repaint was 124 ms
 * with the copy and 54 ms of that was the VERA writes. console.c has the
 * numbers and where they came from. */
void con_putrun_far(uint8_t x, uint8_t y, const char __far *s, uint8_t n);

void con_gotoxy(uint8_t x, uint8_t y);
uint8_t con_getx(void);
uint8_t con_gety(void);

/* The colours everything printed FROM NOW ON is written with -- a pen, not a
 * repaint, so text already on screen keeps the attribute it went down with.
 * con_cls is the exception and fills with the current one.
 *
 * Both are 0-15. This is the same thing K_CON_COLOR does for a program that
 * came in through the jump table; it was reachable from C all along and
 * simply had no declaration here. */
void con_color(uint8_t fg, uint8_t bg);

/* ---- reading keys -------------------------------------------------------
 *
 * Sixteen bits, not eight, and the top byte is what makes it unambiguous:
 *
 *     0x0000          nothing waiting (con_getkey only)
 *     0x0001..0x00FF  a CHARACTER -- CP437, so $41 is 'A' and $B0 is a shade
 *     0x0100 | n      a KEY with no character, n being its position number
 *     0x0200 | c      Ctrl held for a character key
 *     0x0300 | n      Ctrl held for a key with no character
 *     0x0400 | c      Alt held for a character key
 *     0x0500 | n      Alt held for a key with no character
 *
 * F1 and the CP437 glyph at $70 cannot be told apart in eight bits, and both
 * are things a program legitimately receives. Rather than invent control codes
 * for the keys that lack characters -- a table to keep in step with nothing --
 * the key number is reported directly. The low byte is then exactly what
 * KEYSCAN.BIN measures, so the two can never drift. Ctrl and Alt are stateful
 * modifiers like Shift, so they do not arrive alone; they classify the next
 * key event instead. Classes are bit flags, so Ctrl+Alt can combine them.
 *
 * Existing code is unaffected: a comparison against a character still works,
 * and a special key simply matches nothing.
 */

/* MEASURED ON HARDWARE with KEYSCAN.BIN, and every one agrees with
   X816_core rtl/smc_x16.sv and with the emulator's keynum_from_SDL_Scancode.
   Worth stating: the last time these were assumed rather than measured they
   were wrong in both places at once, and agreed with each other. */
#define KEY_F1       (KEY_SPECIAL | 112)
#define KEY_F2       (KEY_SPECIAL | 113)
#define KEY_F3       (KEY_SPECIAL | 114)
#define KEY_F4       (KEY_SPECIAL | 115)
#define KEY_F5       (KEY_SPECIAL | 116)
#define KEY_F6       (KEY_SPECIAL | 117)
#define KEY_F7       (KEY_SPECIAL | 118)
#define KEY_F8       (KEY_SPECIAL | 119)
#define KEY_F9       (KEY_SPECIAL | 120)
#define KEY_F10      (KEY_SPECIAL | 121)
#define KEY_F11      (KEY_SPECIAL | 122)
/* ---- CLAIMED BY MiSTer -- these never reach the core --------------------
 *
 * The framework takes them first: F12 opens the OSD, Scroll Lock switches
 * joystick, Num Lock remaps keyboard/joystick, and Pause does its own thing.
 * Binding any of them works in the EMULATOR and silently does nothing on the
 * board, which is the worst possible way for a key binding to fail.
 *
 * They are defined anyway, so that the names exist and nobody rediscovers
 * this by wiring one up. Do not use them. F1-F11 are yours.
 */
#define KEY_F12      (KEY_SPECIAL | 123)   /* OSD menu                     */

#define KEY_INS      (KEY_SPECIAL | 75)
#define KEY_HOME     (KEY_SPECIAL | 80)
#define KEY_END      (KEY_SPECIAL | 81)
#define KEY_PGUP     (KEY_SPECIAL | 85)
#define KEY_PGDN     (KEY_SPECIAL | 86)
#define KEY_LEFT     (KEY_SPECIAL | 79)
#define KEY_RIGHT    (KEY_SPECIAL | 89)
#define KEY_UP       (KEY_SPECIAL | 83)
#define KEY_DOWN     (KEY_SPECIAL | 84)
/* Modifiers and the keys with no character. Shift, Ctrl, Alt AND Caps Lock
   are handled inside con_getkey and never arrive here alone -- Caps Lock is a
   toggle that upper-cases letters (and inverts Shift for them, PC-style);
   both its edges are consumed. GUI keys still arrive as ordinary special
   keys. KEY_CAPS stays defined so nobody rebinds position 30. */
#define KEY_CAPS     (KEY_SPECIAL | 30)
#define KEY_LCTRL    (KEY_SPECIAL | 58)
#define KEY_LWIN     (KEY_SPECIAL | 59)
#define KEY_LALT     (KEY_SPECIAL | 60)
#define KEY_RALT     (KEY_SPECIAL | 62)
/* Right GUI is 63 per rtl/smc_x16.sv, but the keyboard used for the hardware
   scan has no such key -- both prompts answered 65, which is Menu. So 63 is
   from the RTL and 65 is measured. */
#define KEY_RWIN     (KEY_SPECIAL | 63)
#define KEY_RCTRL    (KEY_SPECIAL | 64)
#define KEY_MENU     (KEY_SPECIAL | 65)
#define KEY_PRTSCR   (KEY_SPECIAL | 124)

#define KEY_NUMLOCK  (KEY_SPECIAL | 90)    /* keyboard/joystick mapping    */
#define KEY_SCRLK    (KEY_SPECIAL | 125)   /* switch joystick              */
#define KEY_PAUSE    (KEY_SPECIAL | 126)   /* claimed by MiSTer            */

/* Non-blocking: returns 0 if no key is waiting. */
uint16_t con_getkey(void);

/* Blocking. */
uint16_t con_getc(void);

/* The RAW byte the SMC returned, before the release-flag and keymap filtering.
 * For diagnostics only, and it distinguishes the failure modes at a glance:
 *     $FE   the transaction is not reaching the SMC at all
 *     $00   the bus works and the key FIFO is simply empty
 *     other a keycode -- the bus is fine and the fault is above this layer
 */
uint8_t con_smc_raw(void);

/* ---- the blinking cursor (runtime/ccursor.s) ----------------------------
 *
 * Driven by the VSYNC interrupt through IRQ_SET, so it costs nothing between
 * frames and nothing at all until it is switched on. It draws by reversing
 * the cell's ATTRIBUTE, so the character underneath is never disturbed.
 *
 * Requires kirq_install() to have run -- without a dispatcher the handler is
 * never called and the cursor simply never appears.
 *
 * A program that takes the screen should call ccur_off() first; the cursor
 * follows con_curx/con_cury and would otherwise blink over whatever the
 * program draws. */
void ccur_on(void);
void ccur_off(void);

/* console.c's cursor position. Exposed for ccursor.s, which reads them every
 * VSYNC; nothing else should write them. */
extern uint8_t con_curx, con_cury;

#endif /* CONSOLE_H */
