/* ==========================================================================
 * console.h -- the X816 console: VERA text out, SMC keyboard in.
 *
 * This is the kernel's console layer, specified in X816_Core doc/KERNEL.md
 * §5.1. It owns the text screen when no program has taken it, which is what
 * puts it kernel-side under §2.1 test 1 -- two copies would fight over the
 * screen and the keyboard queue.
 *
 * 80x60 at 640x480, 1bpp tile mode with per-cell attributes: the same VERA
 * setup already proven on hardware by X816_Core boot/hello.s, rather than a
 * fresh one.
 *
 * BUILD AT -O0. Every one of these functions reaches VERA and the VIA through
 * volatile registers, and Calypsi 5.18 eliminates volatile reads at -O1 and
 * above -- see the README.
 * ========================================================================== */

#ifndef CONSOLE_H
#define CONSOLE_H

#include <stdint.h>
#include <stdbool.h>

#define CON_COLS 80
#define CON_ROWS 60

/* Sets up VERA, uploads the font and clears the screen. Call once. */
void con_init(void);

void con_cls(void);

/* ALL 256 codes have a glyph: CP437, generated by X816_core/tools/mkfont.py.
 * $20-$7E is ASCII including lower case, $80-$FF is CP437's accented letters,
 * box drawing, blocks and maths. Only the control codes below are intercepted:
 *     \n  newline, scrolling at the bottom
 *     \r  carriage return, column 0
 *     \b  backspace, non-destructive at column 0
 */
void con_putc(char c);
void con_puts(const char *s);

/* Through a 24-bit pointer: the kernel ABI hands strings over as address plus
   bank, and a near pointer cannot leave bank $00. */
void con_puts_far(const char __far *s);

/* Place one glyph by CODE, with no interpretation at all.
 *
 * con_putc intercepts $08, $0A and $0D as backspace, newline and carriage
 * return, so those three glyphs are unreachable through it -- and CP437 has
 * real pictures there. Anything drawing with the box, block or control-code
 * glyphs wants this instead: it moves no cursor and interprets nothing. */
void con_putraw(uint8_t x, uint8_t y, uint8_t ch);

void con_gotoxy(uint8_t x, uint8_t y);
uint8_t con_getx(void);
uint8_t con_gety(void);

/* Non-blocking: returns 0 if no key is waiting. */
char con_getkey(void);

/* Blocking. */
char con_getc(void);

/* The RAW byte the SMC returned, before the release-flag and keymap filtering.
 * For diagnostics only, and it distinguishes the failure modes at a glance:
 *     $FE   the transaction is not reaching the SMC at all
 *     $00   the bus works and the key FIFO is simply empty
 *     other a keycode -- the bus is fine and the fault is above this layer
 */
uint8_t con_smc_raw(void);

#endif /* CONSOLE_H */
